### PR TITLE
Complete plaso timeline integration, syslog rewrite, and admin tools subdir

### PR DESCRIPTION
**Pull request by marcurdy**
Tell me how you like it.  I'd like to work on furthering grok patterns and improving dashes in the future

### CODE REVIEW

**Comment by marcurdy** [comment]
Forgot to add the updated load_all_dashboards.sh

**Comment by philhagen** [comment]
This is looking really interesting, @marcurdy - thanks! It's going to take a bit to digest and test but I didn't want you to think anything's been overlooked.
Also, can you help me to understand why my syslog dashboards were removed? (eg /dashboards/syslog/visualization/*)

**Comment by marcurdy** [comment]
The syslog dash had the facility/level in a chart but nothing that truly
made a good analysis of the data.  I did a direct replacement with my
syslog dash, but clearly if that is in your mind against your direction,
rename mine and add that rename to the load_all_dashboards script.

Cheers

**Comment by philhagen** [comment]
Could you please resubmit this as several different, single-purpose PRs?   Rebase against current the 'develop' branch first - no major changes from what you had previously but will make the merge much easier.
PR 1) Timeline parsers, dashboards, visualizations, etc.  Put config files into the /configfiles-UNSUPPORTED/ directory.  The output config mod still goes to the 900- file in the /configfiles/ directory
PR 2) The supporting bash scripts
PR 3) The syslog viz/dash/etc after being put into a new dashboard.  The SSH parser is doing both SSH and PAM, though.  We have PAM handling in the "160-syslog_pam.conf" file.  Also, the SSH parser modifications break some design guidelines I haven't had a chance to document yet (very sorry about that - working to rectify).  The only big one is that the IP addresses need to go into ssh_src_ip, not just src_ip.  Put these mods into a parser that goes into the /configfiles-UNSUPPORTED/ directory until we can get it into the test queue and validate existing functionality is not lost.  The sudo/su one goes to UNSUPPORTED as well - until we get the testing done.

I apologize for the lack of PR documentation - didn't expect to have such a big submission so soon.  Main goals are to make them easy to merge.

**Comment by marcurdy** [comment]
PR 1 completed.  I will need to put time into resorting my syslog lines for
how I determine successful or failed logins and invalid id's for PR#3.

Mark
mark.mccurdy@mail.com
HP Enterprise Digital Investigative Services

**Comment by philhagen** [comment]
Thanks a ton, Mark - this will make things a lot easier to manage.  I'm also using your PRs as test cases against the intended PR guidelines.  I'm closing this PR (the original one) and will work on the one you've just submitted.  Again, thanks a ton!!!

**Pull request closed without merging**
